package com.michaelsanchezjr228;

public class Data {

    private final static int FBS_TEAMS = 134;
    private final static int FCS_WINS = 6;
    private final static int CURRENT_WEEK = 6;

    public static int getFBSTeams() {
        return FBS_TEAMS;
    }

    public static int getFCSWins() {
        return FCS_WINS;
    }

    public static int getCurrentWeek() {
        return CURRENT_WEEK;
    }

    public static void addGames(int week) {
        Calculations.resetGames();
        if (week < 0)
            return;
        Calculations.addGame("0", "true", "Georgia Tech", "fbs", "24", "Florida State", "fbs", "21");
        Calculations.addGame("0", "false", "New Mexico", "fbs", "31", "Montana State", "fcs", "35");
        Calculations.addGame("0", "false", "Nevada", "fbs", "24", "SMU", "fbs", "29");
        Calculations.addGame("0", "false", "Hawai'i", "fbs", "35", "Delaware State", "fcs", "14");
        if (week < 1)
            return;
        Calculations.addGame("1", "false", "Rutgers", "fbs", "44", "Howard", "fcs", "7");
        Calculations.addGame("1", "false", "UL Monroe", "fbs", "30", "Jackson State", "fcs", "14");
        Calculations.addGame("1", "false", "Wake Forest", "fbs", "45", "North Carolina A&T", "fcs", "13");
        Calculations.addGame("1", "false", "NC State", "fbs", "38", "Western Carolina", "fcs", "21");
        Calculations.addGame("1", "false", "Bowling Green", "fbs", "41", "Fordham", "fcs", "17");
        Calculations.addGame("1", "false", "Buffalo", "fbs", "30", "Lafayette", "fcs", "13");
        Calculations.addGame("1", "false", "UCF", "fbs", "57", "New Hampshire", "fcs", "3");
        Calculations.addGame("1", "false", "Central Michigan", "fbs", "66", "Central Connecticut", "fcs",
                "10");
        Calculations.addGame("1", "true", "Arkansas", "fbs", "70", "Arkansas-Pine Bluff", "fcs", "0");
        Calculations.addGame("1", "false", "Toledo", "fbs", "49", "Duquesne", "fcs", "10");
        Calculations.addGame("1", "false", "Minnesota", "fbs", "17", "North Carolina", "fbs", "19");
        Calculations.addGame("1", "false", "Tulsa", "fbs", "62", "Northwestern State", "fcs", "28");
        Calculations.addGame("1", "false", "Tulane", "fbs", "52", "SE Louisiana", "fcs", "0");
        Calculations.addGame("1", "false", "Colorado", "fbs", "31", "North Dakota State", "fcs", "26");
        Calculations.addGame("1", "false", "Missouri", "fbs", "51", "Murray State", "fcs", "0");
        Calculations.addGame("1", "true", "Kansas", "fbs", "48", "Lindenwood", "fcs", "3");
        Calculations.addGame("1", "false", "UAB", "fbs", "41", "Alcorn State", "fcs", "3");
        Calculations.addGame("1", "false", "Jacksonville State", "fbs", "27", "Coastal Carolina", "fbs",
                "55");
        Calculations.addGame("1", "false", "Illinois", "fbs", "45", "Eastern Illinois", "fcs", "0");
        Calculations.addGame("1", "false", "Utah", "fbs", "49", "Southern Utah", "fcs", "0");
        Calculations.addGame("1", "false", "San José State", "fbs", "42", "Sacramento State", "fcs", "24");
        Calculations.addGame("1", "false", "Army", "fbs", "42", "Lehigh", "fcs", "7");
        Calculations.addGame("1", "false", "Oklahoma", "fbs", "51", "Temple", "fbs", "3");
        Calculations.addGame("1", "false", "Michigan State", "fbs", "16", "Florida Atlantic", "fbs", "10");
        Calculations.addGame("1", "false", "Duke", "fbs", "26", "Elon", "fcs", "3");
        Calculations.addGame("1", "false", "Wisconsin", "fbs", "28", "Western Michigan", "fbs", "14");
        Calculations.addGame("1", "false", "Stanford", "fbs", "27", "TCU", "fbs", "34");
        Calculations.addGame("1", "false", "Utah State", "fbs", "36", "Robert Morris", "fcs", "14");
        Calculations.addGame("1", "false", "Louisville", "fbs", "62", "Austin Peay", "fcs", "0");
        Calculations.addGame("1", "false", "Navy", "fbs", "49", "Bucknell", "fcs", "21");
        Calculations.addGame("1", "true", "Georgia", "fbs", "34", "Clemson", "fbs", "3");
        Calculations.addGame("1", "false", "West Virginia", "fbs", "12", "Penn State", "fbs", "34");
        Calculations.addGame("1", "false", "Vanderbilt", "fbs", "34", "Virginia Tech", "fbs", "27");
        Calculations.addGame("1", "false", "Maryland", "fbs", "50", "UConn", "fbs", "7");
        Calculations.addGame("1", "false", "Purdue", "fbs", "49", "Indiana State", "fcs", "0");
        Calculations.addGame("1", "false", "Iowa", "fbs", "40", "Illinois State", "fcs", "0");
        Calculations.addGame("1", "false", "Pittsburgh", "fbs", "55", "Kent State", "fbs", "24");
        Calculations.addGame("1", "false", "Tennessee", "fbs", "69", "Chattanooga", "fcs", "3");
        Calculations.addGame("1", "false", "Oklahoma State", "fbs", "44", "South Dakota State", "fcs",
                "20");
        Calculations.addGame("1", "false", "Cincinnati", "fbs", "38", "Towson", "fcs", "20");
        Calculations.addGame("1", "false", "Washington State", "fbs", "70", "Portland State", "fcs", "30");
        Calculations.addGame("1", "false", "Texas", "fbs", "52", "Colorado State", "fbs", "0");
        Calculations.addGame("1", "false", "Northern Illinois", "fbs", "54", "Western Illinois", "fcs",
                "15");
        Calculations.addGame("1", "false", "App State", "fbs", "38", "East Tennessee State", "fcs", "10");
        Calculations.addGame("1", "false", "Air Force", "fbs", "21", "Merrimack", "fcs", "6");
        Calculations.addGame("1", "false", "UTSA", "fbs", "28", "Kennesaw State", "fbs", "16");
        Calculations.addGame("1", "false", "Massachusetts", "fbs", "14", "Eastern Michigan", "fbs", "28");
        Calculations.addGame("1", "false", "Syracuse", "fbs", "38", "Ohio", "fbs", "22");
        Calculations.addGame("1", "false", "Iowa State", "fbs", "21", "North Dakota", "fcs", "3");
        Calculations.addGame("1", "false", "Ohio State", "fbs", "52", "Akron", "fbs", "6");
        Calculations.addGame("1", "false", "Nebraska", "fbs", "40", "UTEP", "fbs", "7");
        Calculations.addGame("1", "false", "Florida", "fbs", "17", "Miami", "fbs", "41");
        Calculations.addGame("1", "true", "Northwestern", "fbs", "13", "Miami (OH)", "fbs", "6");
        Calculations.addGame("1", "false", "Indiana", "fbs", "31", "Florida International", "fbs", "7");
        Calculations.addGame("1", "false", "Georgia Southern", "fbs", "45", "Boise State", "fbs", "56");
        Calculations.addGame("1", "false", "South Carolina", "fbs", "23", "Old Dominion", "fbs", "19");
        Calculations.addGame("1", "false", "Marshall", "fbs", "45", "Stony Brook", "fcs", "3");
        Calculations.addGame("1", "false", "South Alabama", "fbs", "38", "North Texas", "fbs", "52");
        Calculations.addGame("1", "false", "California", "fbs", "31", "UC Davis", "fcs", "13");
        Calculations.addGame("1", "false", "East Carolina", "fbs", "42", "Norfolk State", "fcs", "3");
        Calculations.addGame("1", "false", "Mississippi State", "fbs", "56", "Eastern Kentucky", "fcs",
                "7");
        Calculations.addGame("1", "false", "Liberty", "fbs", "41", "Campbell", "fcs", "24");
        Calculations.addGame("1", "false", "Virginia", "fbs", "34", "Richmond", "fcs", "13");
        Calculations.addGame("1", "false", "Oregon State", "fbs", "38", "Idaho State", "fcs", "15");
        Calculations.addGame("1", "false", "Alabama", "fbs", "63", "Western Kentucky", "fbs", "0");
        Calculations.addGame("1", "false", "Memphis", "fbs", "40", "North Alabama", "fcs", "0");
        Calculations.addGame("1", "false", "South Florida", "fbs", "48", "Bethune-Cookman", "fcs", "3");
        Calculations.addGame("1", "false", "Rice", "fbs", "14", "Sam Houston", "fbs", "34");
        Calculations.addGame("1", "false", "Arkansas State", "fbs", "34", "Central Arkansas", "fcs", "31");
        Calculations.addGame("1", "false", "Ole Miss", "fbs", "76", "Furman", "fcs", "0");
        Calculations.addGame("1", "false", "Kansas State", "fbs", "41", "UT Martin", "fcs", "6");
        Calculations.addGame("1", "false", "Baylor", "fbs", "45", "Tarleton State", "fcs", "3");
        Calculations.addGame("1", "false", "Troy", "fbs", "26", "Nevada", "fbs", "28");
        Calculations.addGame("1", "false", "Houston", "fbs", "7", "UNLV", "fbs", "27");
        Calculations.addGame("1", "false", "Middle Tennessee", "fbs", "32", "Tennessee Tech", "fcs", "25");
        Calculations.addGame("1", "false", "Hawai'i", "fbs", "13", "UCLA", "fbs", "16");
        Calculations.addGame("1", "false", "Texas Tech", "fbs", "52", "Abilene Christian", "fcs", "51");
        Calculations.addGame("1", "false", "Texas A&M", "fbs", "13", "Notre Dame", "fbs", "23");
        Calculations.addGame("1", "false", "Michigan", "fbs", "30", "Fresno State", "fbs", "10");
        Calculations.addGame("1", "false", "Auburn", "fbs", "73", "Alabama A&M", "fcs", "3");
        Calculations.addGame("1", "false", "Oregon", "fbs", "24", "Idaho", "fcs", "14");
        Calculations.addGame("1", "false", "Kentucky", "fbs", "31", "Southern Miss", "fbs", "0");
        Calculations.addGame("1", "false", "Charlotte", "fbs", "7", "James Madison", "fbs", "30");
        Calculations.addGame("1", "false", "SMU", "fbs", "59", "Houston Christian", "fcs", "7");
        Calculations.addGame("1", "false", "Georgia Tech", "fbs", "35", "Georgia State", "fbs", "12");
        Calculations.addGame("1", "false", "Louisiana", "fbs", "40", "Grambling", "fcs", "10");
        Calculations.addGame("1", "false", "Texas State", "fbs", "34", "Lamar", "fcs", "27");
        Calculations.addGame("1", "false", "Louisiana Tech", "fbs", "25", "Nicholls", "fcs", "17");
        Calculations.addGame("1", "false", "San Diego State", "fbs", "45", "East Texas A&M", "fcs", "14");
        Calculations.addGame("1", "false", "BYU", "fbs", "41", "Southern Illinois", "fcs", "13");
        Calculations.addGame("1", "false", "New Mexico State", "fbs", "23", "Southeast Missouri State",
                "fcs",
                "16");
        Calculations.addGame("1", "false", "Arizona", "fbs", "61", "New Mexico", "fbs", "39");
        Calculations.addGame("1", "false", "Arizona State", "fbs", "48", "Wyoming", "fbs", "7");
        Calculations.addGame("1", "false", "Washington", "fbs", "35", "Weber State", "fcs", "3");
        Calculations.addGame("1", "true", "LSU", "fbs", "20", "USC", "fbs", "27");
        Calculations.addGame("1", "false", "Florida State", "fbs", "13", "Boston College", "fbs", "28");
        if (week < 2)
            return;
        Calculations.addGame("2", "false", "SMU", "fbs", "15", "BYU", "fbs", "18");
        Calculations.addGame("2", "false", "Indiana", "fbs", "77", "Western Illinois", "fcs", "3");
        Calculations.addGame("2", "true", "Northwestern", "fbs", "20", "Duke", "fbs", "26");
        Calculations.addGame("2", "false", "Cincinnati", "fbs", "27", "Pittsburgh", "fbs", "28");
        Calculations.addGame("2", "false", "UConn", "fbs", "63", "Merrimack", "fcs", "17");
        Calculations.addGame("2", "false", "Memphis", "fbs", "38", "Troy", "fbs", "17");
        Calculations.addGame("2", "false", "Florida Atlantic", "fbs", "7", "Army", "fbs", "24");
        Calculations.addGame("2", "false", "Michigan", "fbs", "12", "Texas", "fbs", "31");
        Calculations.addGame("2", "false", "Penn State", "fbs", "34", "Bowling Green", "fbs", "27");
        Calculations.addGame("2", "false", "Syracuse", "fbs", "31", "Georgia Tech", "fbs", "28");
        Calculations.addGame("2", "false", "Rutgers", "fbs", "49", "Akron", "fbs", "17");
        Calculations.addGame("2", "false", "Minnesota", "fbs", "48", "Rhode Island", "fcs", "0");
        Calculations.addGame("2", "false", "Oklahoma State", "fbs", "39", "Arkansas", "fbs", "31");
        Calculations.addGame("2", "false", "Tulane", "fbs", "27", "Kansas State", "fbs", "34");
        Calculations.addGame("2", "false", "Texas A&M", "fbs", "52", "McNeese", "fcs", "10");
        Calculations.addGame("2", "false", "Ball State", "fbs", "42", "Missouri State", "fcs", "34");
        Calculations.addGame("2", "false", "Georgia", "fbs", "48", "Tennessee Tech", "fcs", "3");
        Calculations.addGame("2", "false", "Kent State", "fbs", "17", "St. Francis (PA)", "fcs", "23");
        Calculations.addGame("2", "false", "UNLV", "fbs", "72", "Utah Tech", "fcs", "14");
        Calculations.addGame("2", "false", "Toledo", "fbs", "38", "Massachusetts", "fbs", "23");
        Calculations.addGame("2", "false", "Wyoming", "fbs", "13", "Idaho", "fcs", "17");
        Calculations.addGame("2", "false", "Boston College", "fbs", "56", "Duquesne", "fcs", "0");
        Calculations.addGame("2", "false", "Notre Dame", "fbs", "14", "Northern Illinois", "fbs", "16");
        Calculations.addGame("2", "false", "Navy", "fbs", "38", "Temple", "fbs", "11");
        Calculations.addGame("2", "false", "Wisconsin", "fbs", "27", "South Dakota", "fcs", "13");
        Calculations.addGame("2", "false", "Utah", "fbs", "23", "Baylor", "fbs", "12");
        Calculations.addGame("2", "false", "Iowa", "fbs", "19", "Iowa State", "fbs", "20");
        Calculations.addGame("2", "false", "Louisville", "fbs", "49", "Jacksonville State", "fbs", "14");
        Calculations.addGame("2", "false", "Auburn", "fbs", "14", "California", "fbs", "21");
        Calculations.addGame("2", "false", "Kentucky", "fbs", "6", "South Carolina", "fbs", "31");
        Calculations.addGame("2", "false", "Maryland", "fbs", "24", "Michigan State", "fbs", "27");
        Calculations.addGame("2", "false", "Washington", "fbs", "30", "Eastern Michigan", "fbs", "9");
        Calculations.addGame("2", "false", "North Carolina", "fbs", "38", "Charlotte", "fbs", "20");
        Calculations.addGame("2", "false", "Texas State", "fbs", "49", "UTSA", "fbs", "10");
        Calculations.addGame("2", "false", "Ole Miss", "fbs", "52", "Middle Tennessee", "fbs", "3");
        Calculations.addGame("2", "false", "Virginia Tech", "fbs", "31", "Marshall", "fbs", "14");
        Calculations.addGame("2", "false", "Ohio", "fbs", "27", "South Alabama", "fbs", "20");
        Calculations.addGame("2", "false", "Miami", "fbs", "56", "Florida A&M", "fcs", "9");
        Calculations.addGame("2", "true", "Florida International", "fbs", "52", "Central Michigan", "fbs",
                "16");
        Calculations.addGame("2", "false", "Old Dominion", "fbs", "14", "East Carolina", "fbs", "20");
        Calculations.addGame("2", "false", "West Virginia", "fbs", "49", "UAlbany", "fcs", "14");
        Calculations.addGame("2", "false", "James Madison", "fbs", "13", "Gardner-Webb", "fcs", "6");
        Calculations.addGame("2", "false", "UCF", "fbs", "45", "Sam Houston", "fbs", "14");
        Calculations.addGame("2", "false", "Nevada", "fbs", "17", "Georgia Southern", "fbs", "20");
        Calculations.addGame("2", "false", "Arkansas State", "fbs", "28", "Tulsa", "fbs", "24");
        Calculations.addGame("2", "false", "UL Monroe", "fbs", "32", "UAB", "fbs", "6");
        Calculations.addGame("2", "false", "Air Force", "fbs", "7", "San José State", "fbs", "17");
        Calculations.addGame("2", "false", "Illinois", "fbs", "23", "Kansas", "fbs", "17");
        Calculations.addGame("2", "false", "Missouri", "fbs", "38", "Buffalo", "fbs", "0");
        Calculations.addGame("2", "false", "Alabama", "fbs", "42", "South Florida", "fbs", "16");
        Calculations.addGame("2", "false", "Georgia State", "fbs", "24", "Chattanooga", "fcs", "21");
        Calculations.addGame("2", "false", "Florida", "fbs", "45", "Samford", "fcs", "7");
        Calculations.addGame("2", "false", "Coastal Carolina", "fbs", "40", "William & Mary", "fcs", "21");
        Calculations.addGame("2", "false", "Western Kentucky", "fbs", "31", "Eastern Kentucky", "fcs", "0");
        Calculations.addGame("2", "false", "Stanford", "fbs", "41", "Cal Poly", "fcs", "7");
        Calculations.addGame("2", "false", "Colorado State", "fbs", "38", "Northern Colorado", "fcs", "17");
        Calculations.addGame("2", "false", "Southern Miss", "fbs", "35", "SE Louisiana", "fcs", "10");
        Calculations.addGame("2", "false", "Rice", "fbs", "69", "Texas Southern", "fcs", "7");
        Calculations.addGame("2", "false", "Wake Forest", "fbs", "30", "Virginia", "fbs", "31");
        Calculations.addGame("2", "false", "Kennesaw State", "fbs", "10", "Louisiana", "fbs", "34");
        Calculations.addGame("2", "false", "Ohio State", "fbs", "56", "Western Michigan", "fbs", "0");
        Calculations.addGame("2", "false", "North Texas", "fbs", "35", "Stephen F. Austin", "fcs", "20");
        Calculations.addGame("2", "false", "LSU", "fbs", "44", "Nicholls", "fcs", "21");
        Calculations.addGame("2", "true", "NC State", "fbs", "10", "Tennessee", "fbs", "51");
        Calculations.addGame("2", "false", "Vanderbilt", "fbs", "55", "Alcorn State", "fcs", "0");
        Calculations.addGame("2", "false", "Nebraska", "fbs", "28", "Colorado", "fbs", "10");
        Calculations.addGame("2", "false", "Oklahoma", "fbs", "16", "Houston", "fbs", "12");
        Calculations.addGame("2", "false", "TCU", "fbs", "45", "Long Island University", "fcs", "0");
        Calculations.addGame("2", "false", "Clemson", "fbs", "66", "App State", "fbs", "20");
        Calculations.addGame("2", "false", "UTEP", "fbs", "24", "Southern Utah", "fcs", "27");
        Calculations.addGame("2", "false", "Oregon", "fbs", "37", "Boise State", "fbs", "34");
        Calculations.addGame("2", "false", "Fresno State", "fbs", "46", "Sacramento State", "fcs", "30");
        Calculations.addGame("2", "false", "Washington State", "fbs", "37", "Texas Tech", "fbs", "16");
        Calculations.addGame("2", "false", "Arizona", "fbs", "22", "Northern Arizona", "fcs", "10");
        Calculations.addGame("2", "false", "New Mexico State", "fbs", "24", "Liberty", "fbs", "30");
        Calculations.addGame("2", "false", "San Diego State", "fbs", "0", "Oregon State", "fbs", "21");
        Calculations.addGame("2", "false", "Arizona State", "fbs", "30", "Mississippi State", "fbs", "23");
        Calculations.addGame("2", "false", "USC", "fbs", "48", "Utah State", "fbs", "0");
        if (week < 3)
            return;
        Calculations.addGame("3", "false", "South Alabama", "fbs", "87", "Northwestern State", "fcs", "10");
        Calculations.addGame("3", "false", "Texas State", "fbs", "28", "Arizona State", "fbs", "31");
        Calculations.addGame("3", "true", "Kansas", "fbs", "20", "UNLV", "fbs", "23");
        Calculations.addGame("3", "false", "Kansas State", "fbs", "31", "Arizona", "fbs", "7");
        Calculations.addGame("3", "false", "NC State", "fbs", "30", "Louisiana Tech", "fbs", "20");
        Calculations.addGame("3", "false", "Miami (OH)", "fbs", "16", "Cincinnati", "fbs", "27");
        Calculations.addGame("3", "false", "Texas Tech", "fbs", "66", "North Texas", "fbs", "21");
        Calculations.addGame("3", "false", "Florida State", "fbs", "12", "Memphis", "fbs", "20");
        Calculations.addGame("3", "false", "South Carolina", "fbs", "33", "LSU", "fbs", "36");
        Calculations.addGame("3", "false", "Michigan", "fbs", "28", "Arkansas State", "fbs", "18");
        Calculations.addGame("3", "false", "Illinois", "fbs", "30", "Central Michigan", "fbs", "9");
        Calculations.addGame("3", "false", "Tulsa", "fbs", "10", "Oklahoma State", "fbs", "45");
        Calculations.addGame("3", "false", "Wisconsin", "fbs", "10", "Alabama", "fbs", "42");
        Calculations.addGame("3", "false", "Missouri", "fbs", "27", "Boston College", "fbs", "21");
        Calculations.addGame("3", "false", "Buffalo", "fbs", "34", "Massachusetts", "fbs", "3");
        Calculations.addGame("3", "false", "Temple", "fbs", "20", "Coastal Carolina", "fbs", "28");
        Calculations.addGame("3", "false", "Georgia Tech", "fbs", "59", "VMI", "fcs", "7");
        Calculations.addGame("3", "false", "Michigan State", "fbs", "40", "Prairie View A&M", "fcs", "0");
        Calculations.addGame("3", "false", "Ohio", "fbs", "21", "Morgan State", "fcs", "6");
        Calculations.addGame("3", "false", "Oregon State", "fbs", "14", "Oregon", "fbs", "49");
        Calculations.addGame("3", "false", "Miami", "fbs", "62", "Ball State", "fbs", "0");
        Calculations.addGame("3", "false", "Oklahoma", "fbs", "34", "Tulane", "fbs", "19");
        Calculations.addGame("3", "false", "Purdue", "fbs", "7", "Notre Dame", "fbs", "66");
        Calculations.addGame("3", "false", "Florida", "fbs", "20", "Texas A&M", "fbs", "33");
        Calculations.addGame("3", "false", "Minnesota", "fbs", "27", "Nevada", "fbs", "0");
        Calculations.addGame("3", "true", "Washington", "fbs", "19", "Washington State", "fbs", "24");
        Calculations.addGame("3", "false", "Pittsburgh", "fbs", "38", "West Virginia", "fbs", "34");
        Calculations.addGame("3", "false", "East Carolina", "fbs", "19", "App State", "fbs", "21");
        Calculations.addGame("3", "false", "Iowa", "fbs", "38", "Troy", "fbs", "21");
        Calculations.addGame("3", "false", "Arkansas", "fbs", "37", "UAB", "fbs", "27");
        Calculations.addGame("3", "false", "Utah State", "fbs", "21", "Utah", "fbs", "38");
        Calculations.addGame("3", "false", "Liberty", "fbs", "28", "UTEP", "fbs", "10");
        Calculations.addGame("3", "false", "Duke", "fbs", "26", "UConn", "fbs", "21");
        Calculations.addGame("3", "false", "Old Dominion", "fbs", "17", "Virginia Tech", "fbs", "37");
        Calculations.addGame("3", "false", "Florida Atlantic", "fbs", "38", "Florida International", "fbs", "20");
        Calculations.addGame("3", "false", "North Carolina", "fbs", "45", "North Carolina Central", "fcs", "10");
        Calculations.addGame("3", "false", "Georgia Southern", "fbs", "42", "South Carolina State", "fcs", "14");
        Calculations.addGame("3", "false", "Akron", "fbs", "31", "Colgate", "fcs", "20");
        Calculations.addGame("3", "false", "Charlotte", "fbs", "27", "Gardner-Webb", "fcs", "26");
        Calculations.addGame("3", "false", "Wake Forest", "fbs", "6", "Ole Miss", "fbs", "40");
        Calculations.addGame("3", "false", "Western Michigan", "fbs", "59", "Bethune-Cookman", "fcs", "31");
        Calculations.addGame("3", "false", "Georgia State", "fbs", "36", "Vanderbilt", "fbs", "32");
        Calculations.addGame("3", "false", "Texas", "fbs", "56", "UTSA", "fbs", "7");
        Calculations.addGame("3", "false", "Southern Miss", "fbs", "24", "South Florida", "fbs", "49");
        Calculations.addGame("3", "false", "Sam Houston", "fbs", "31", "Hawai'i", "fbs", "13");
        Calculations.addGame("3", "false", "San José State", "fbs", "31", "Kennesaw State", "fbs", "10");
        Calculations.addGame("3", "false", "Middle Tennessee", "fbs", "21", "Western Kentucky", "fbs", "49");
        Calculations.addGame("3", "false", "Eastern Michigan", "fbs", "37", "Jacksonville State", "fbs", "34");
        Calculations.addGame("3", "false", "Auburn", "fbs", "45", "New Mexico", "fbs", "19");
        Calculations.addGame("3", "false", "UCLA", "fbs", "13", "Indiana", "fbs", "42");
        Calculations.addGame("3", "false", "Baylor", "fbs", "31", "Air Force", "fbs", "3");
        Calculations.addGame("3", "false", "Colorado State", "fbs", "9", "Colorado", "fbs", "28");
        Calculations.addGame("3", "false", "TCU", "fbs", "34", "UCF", "fbs", "35");
        Calculations.addGame("3", "false", "Nebraska", "fbs", "34", "Northern Iowa", "fcs", "3");
        Calculations.addGame("3", "false", "Kentucky", "fbs", "12", "Georgia", "fbs", "13");
        Calculations.addGame("3", "true", "Northwestern", "fbs", "31", "Eastern Illinois", "fcs", "7");
        Calculations.addGame("3", "false", "Mississippi State", "fbs", "17", "Toledo", "fbs", "41");
        Calculations.addGame("3", "false", "Tennessee", "fbs", "71", "Kent State", "fbs", "0");
        Calculations.addGame("3", "false", "Houston", "fbs", "33", "Rice", "fbs", "7");
        Calculations.addGame("3", "false", "Virginia", "fbs", "13", "Maryland", "fbs", "27");
        Calculations.addGame("3", "false", "Wyoming", "fbs", "14", "BYU", "fbs", "34");
        Calculations.addGame("3", "false", "Fresno State", "fbs", "48", "New Mexico State", "fbs", "0");
        Calculations.addGame("3", "false", "California", "fbs", "31", "San Diego State", "fbs", "10");
        if (week < 4)
            return;
        Calculations.addGame("4", "false", "App State", "fbs", "14", "South Alabama", "fbs", "48");
        Calculations.addGame("4", "false", "Syracuse", "fbs", "24", "Stanford", "fbs", "26");
        Calculations.addGame("4", "false", "Nebraska", "fbs", "24", "Illinois", "fbs", "31");
        Calculations.addGame("4", "false", "Washington State", "fbs", "54", "San José State", "fbs", "52");
        Calculations.addGame("4", "false", "Louisiana", "fbs", "33", "Tulane", "fbs", "41");
        Calculations.addGame("4", "false", "Army", "fbs", "37", "Rice", "fbs", "14");
        Calculations.addGame("4", "false", "Maryland", "fbs", "38", "Villanova", "fcs", "20");
        Calculations.addGame("4", "false", "Mississippi State", "fbs", "28", "Florida", "fbs", "45");
        Calculations.addGame("4", "false", "North Carolina", "fbs", "50", "James Madison", "fbs", "70");
        Calculations.addGame("4", "false", "Cincinnati", "fbs", "34", "Houston", "fbs", "0");
        Calculations.addGame("4", "false", "West Virginia", "fbs", "32", "Kansas", "fbs", "28");
        Calculations.addGame("4", "false", "Clemson", "fbs", "59", "NC State", "fbs", "35");
        Calculations.addGame("4", "false", "Ohio State", "fbs", "49", "Marshall", "fbs", "14");
        Calculations.addGame("4", "false", "Indiana", "fbs", "52", "Charlotte", "fbs", "14");
        Calculations.addGame("4", "false", "Kentucky", "fbs", "41", "Ohio", "fbs", "6");
        Calculations.addGame("4", "false", "Central Michigan", "fbs", "37", "Ball State", "fbs", "34");
        Calculations.addGame("4", "false", "Eastern Michigan", "fbs", "36", "St. Francis (PA)", "fcs", "0");
        Calculations.addGame("4", "false", "Iowa State", "fbs", "52", "Arkansas State", "fbs", "7");
        Calculations.addGame("4", "false", "Temple", "fbs", "45", "Utah State", "fbs", "29");
        Calculations.addGame("4", "false", "Coastal Carolina", "fbs", "24", "Virginia", "fbs", "43");
        Calculations.addGame("4", "false", "Nevada", "fbs", "49", "Eastern Washington", "fcs", "16");
        Calculations.addGame("4", "false", "Jacksonville State", "fbs", "44", "Southern Miss", "fbs", "7");
        Calculations.addGame("4", "false", "Louisville", "fbs", "31", "Georgia Tech", "fbs", "19");
        Calculations.addGame("4", "false", "Penn State", "fbs", "56", "Kent State", "fbs", "0");
        Calculations.addGame("4", "false", "Michigan", "fbs", "27", "USC", "fbs", "24");
        Calculations.addGame("4", "false", "LSU", "fbs", "34", "UCLA", "fbs", "17");
        Calculations.addGame("4", "false", "Notre Dame", "fbs", "28", "Miami (OH)", "fbs", "3");
        Calculations.addGame("4", "false", "Northern Illinois", "fbs", "20", "Buffalo", "fbs", "23");
        Calculations.addGame("4", "false", "Auburn", "fbs", "14", "Arkansas", "fbs", "24");
        Calculations.addGame("4", "false", "Virginia Tech", "fbs", "23", "Rutgers", "fbs", "26");
        Calculations.addGame("4", "false", "Texas Tech", "fbs", "30", "Arizona State", "fbs", "22");
        Calculations.addGame("4", "false", "Navy", "fbs", "56", "Memphis", "fbs", "44");
        Calculations.addGame("4", "false", "Massachusetts", "fbs", "35", "Central Connecticut", "fcs", "31");
        Calculations.addGame("4", "false", "Pittsburgh", "fbs", "73", "Youngstown State", "fcs", "17");
        Calculations.addGame("4", "false", "UTSA", "fbs", "45", "Houston Christian", "fcs", "7");
        Calculations.addGame("4", "false", "Oklahoma State", "fbs", "19", "Utah", "fbs", "22");
        Calculations.addGame("4", "false", "Middle Tennessee", "fbs", "17", "Duke", "fbs", "45");
        Calculations.addGame("4", "false", "Missouri", "fbs", "30", "Vanderbilt", "fbs", "27");
        Calculations.addGame("4", "false", "SMU", "fbs", "66", "TCU", "fbs", "42");
        Calculations.addGame("4", "false", "Colorado State", "fbs", "27", "UTEP", "fbs", "17");
        Calculations.addGame("4", "true", "Florida International", "fbs", "42", "Monmouth", "fcs", "45");
        Calculations.addGame("4", "false", "Liberty", "fbs", "35", "East Carolina", "fbs", "24");
        Calculations.addGame("4", "false", "North Texas", "fbs", "44", "Wyoming", "fbs", "17");
        Calculations.addGame("4", "false", "Sam Houston", "fbs", "31", "New Mexico State", "fbs", "11");
        Calculations.addGame("4", "false", "Troy", "fbs", "34", "Florida A&M", "fcs", "12");
        Calculations.addGame("4", "false", "Washington", "fbs", "24", "Northwestern", "fbs", "5");
        Calculations.addGame("4", "false", "UConn", "fbs", "48", "Florida Atlantic", "fbs", "14");
        Calculations.addGame("4", "false", "Florida State", "fbs", "14", "California", "fbs", "9");
        Calculations.addGame("4", "false", "Louisiana Tech", "fbs", "20", "Tulsa", "fbs", "23");
        Calculations.addGame("4", "false", "Western Kentucky", "fbs", "26", "Toledo", "fbs", "21");
        Calculations.addGame("4", "false", "South Florida", "fbs", "15", "Miami", "fbs", "50");
        Calculations.addGame("4", "false", "South Carolina", "fbs", "50", "Akron", "fbs", "7");
        Calculations.addGame("4", "false", "Texas A&M", "fbs", "26", "Bowling Green", "fbs", "20");
        Calculations.addGame("4", "false", "Oklahoma", "fbs", "15", "Tennessee", "fbs", "25");
        Calculations.addGame("4", "false", "Minnesota", "fbs", "14", "Iowa", "fbs", "31");
        Calculations.addGame("4", "false", "Ole Miss", "fbs", "52", "Georgia Southern", "fbs", "13");
        Calculations.addGame("4", "false", "Colorado", "fbs", "38", "Baylor", "fbs", "31");
        Calculations.addGame("4", "false", "Texas", "fbs", "51", "UL Monroe", "fbs", "3");
        Calculations.addGame("4", "false", "Boston College", "fbs", "23", "Michigan State", "fbs", "19");
        Calculations.addGame("4", "false", "New Mexico", "fbs", "21", "Fresno State", "fbs", "38");
        Calculations.addGame("4", "false", "Oregon State", "fbs", "38", "Purdue", "fbs", "21");
        Calculations.addGame("4", "false", "Boise State", "fbs", "56", "Portland State", "fcs", "14");
        Calculations.addGame("4", "false", "BYU", "fbs", "38", "Kansas State", "fbs", "9");
        Calculations.addGame("4", "false", "Hawai'i", "fbs", "36", "Northern Iowa", "fcs", "7");
        if (week < 5)
            return;
        Calculations.addGame("5", "false", "Temple", "fbs", "14", "Army", "fbs", "42");
        Calculations.addGame("5", "false", "Miami", "fbs", "38", "Virginia Tech", "fbs", "34");
        Calculations.addGame("5", "false", "Rutgers", "fbs", "21", "Washington", "fbs", "18");
        Calculations.addGame("5", "false", "Purdue", "fbs", "10", "Nebraska", "fbs", "28");
        Calculations.addGame("5", "false", "UConn", "fbs", "47", "Buffalo", "fbs", "3");
        Calculations.addGame("5", "false", "Boston College", "fbs", "21", "Western Kentucky", "fbs", "20");
        Calculations.addGame("5", "false", "NC State", "fbs", "24", "Northern Illinois", "fbs", "17");
        Calculations.addGame("5", "false", "Syracuse", "fbs", "42", "Holy Cross", "fcs", "14");
        Calculations.addGame("5", "false", "Michigan", "fbs", "27", "Minnesota", "fbs", "24");
        Calculations.addGame("5", "false", "Baylor", "fbs", "28", "BYU", "fbs", "34");
        Calculations.addGame("5", "false", "UAB", "fbs", "18", "Navy", "fbs", "41");
        Calculations.addGame("5", "false", "Indiana", "fbs", "42", "Maryland", "fbs", "28");
        Calculations.addGame("5", "false", "Ole Miss", "fbs", "17", "Kentucky", "fbs", "20");
        Calculations.addGame("5", "false", "Kansas State", "fbs", "42", "Oklahoma State", "fbs", "20");
        Calculations.addGame("5", "false", "Tulane", "fbs", "45", "South Florida", "fbs", "10");
        Calculations.addGame("5", "false", "James Madison", "fbs", "63", "Ball State", "fbs", "7");
        Calculations.addGame("5", "true", "Sam Houston", "fbs", "40", "Texas State", "fbs", "39");
        Calculations.addGame("5", "false", "Kent State", "fbs", "33", "Eastern Michigan", "fbs", "52");
        Calculations.addGame("5", "false", "USC", "fbs", "38", "Wisconsin", "fbs", "21");
        Calculations.addGame("5", "false", "Notre Dame", "fbs", "31", "Louisville", "fbs", "24");
        Calculations.addGame("5", "false", "UCF", "fbs", "21", "Colorado", "fbs", "48");
        Calculations.addGame("5", "false", "Auburn", "fbs", "21", "Oklahoma", "fbs", "27");
        Calculations.addGame("5", "true", "Texas A&M", "fbs", "21", "Arkansas", "fbs", "17");
        Calculations.addGame("5", "false", "Central Michigan", "fbs", "22", "San Diego State", "fbs", "21");
        Calculations.addGame("5", "false", "Georgia State", "fbs", "21", "Georgia Southern", "fbs", "38");
        Calculations.addGame("5", "false", "Marshall", "fbs", "27", "Western Michigan", "fbs", "20");
        Calculations.addGame("5", "false", "Ohio", "fbs", "30", "Akron", "fbs", "10");
        Calculations.addGame("5", "false", "Miami (OH)", "fbs", "23", "Massachusetts", "fbs", "20");
        Calculations.addGame("5", "false", "Wake Forest", "fbs", "38", "Louisiana", "fbs", "41");
        Calculations.addGame("5", "true", "Kansas", "fbs", "27", "TCU", "fbs", "38");
        Calculations.addGame("5", "false", "UNLV", "fbs", "59", "Fresno State", "fbs", "14");
        Calculations.addGame("5", "false", "Duke", "fbs", "21", "North Carolina", "fbs", "20");
        Calculations.addGame("5", "false", "East Carolina", "fbs", "30", "UTSA", "fbs", "20");
        Calculations.addGame("5", "false", "Texas", "fbs", "35", "Mississippi State", "fbs", "13");
        Calculations.addGame("5", "false", "Bowling Green", "fbs", "27", "Old Dominion", "fbs", "30");
        Calculations.addGame("5", "true", "Florida International", "fbs", "17", "Louisiana Tech", "fbs", "10");
        Calculations.addGame("5", "false", "Florida Atlantic", "fbs", "41", "Wagner", "fcs", "10");
        Calculations.addGame("5", "false", "Kennesaw State", "fbs", "13", "UT Martin", "fcs", "24");
        Calculations.addGame("5", "false", "Clemson", "fbs", "40", "Stanford", "fbs", "14");
        Calculations.addGame("5", "false", "Troy", "fbs", "9", "UL Monroe", "fbs", "13");
        Calculations.addGame("5", "false", "Rice", "fbs", "20", "Charlotte", "fbs", "21");
        Calculations.addGame("5", "false", "North Texas", "fbs", "52", "Tulsa", "fbs", "20");
        Calculations.addGame("5", "false", "Houston", "fbs", "0", "Iowa State", "fbs", "20");
        Calculations.addGame("5", "false", "Alabama", "fbs", "41", "Georgia", "fbs", "34");
        Calculations.addGame("5", "false", "Michigan State", "fbs", "7", "Ohio State", "fbs", "38");
        Calculations.addGame("5", "false", "Penn State", "fbs", "21", "Illinois", "fbs", "7");
        Calculations.addGame("5", "false", "Memphis", "fbs", "24", "Middle Tennessee", "fbs", "7");
        Calculations.addGame("5", "false", "LSU", "fbs", "42", "South Alabama", "fbs", "10");
        Calculations.addGame("5", "false", "Wyoming", "fbs", "31", "Air Force", "fbs", "19");
        Calculations.addGame("5", "false", "SMU", "fbs", "42", "Florida State", "fbs", "16");
        Calculations.addGame("5", "false", "Texas Tech", "fbs", "44", "Cincinnati", "fbs", "41");
        Calculations.addGame("5", "false", "New Mexico State", "fbs", "40", "New Mexico", "fbs", "50");
        Calculations.addGame("5", "false", "Boise State", "fbs", "45", "Washington State", "fbs", "24");
        Calculations.addGame("5", "false", "Utah", "fbs", "10", "Arizona", "fbs", "23");
        Calculations.addGame("5", "false", "UCLA", "fbs", "13", "Oregon", "fbs", "34");
        if (week < 6)
            return;
        Calculations.addGame("6", "false", "Troy", "fbs", "17", "Texas State", "fbs", "38");
        Calculations.addGame("6", "false", "UTEP", "fbs", "21", "Sam Houston", "fbs", "41");
        Calculations.addGame("6", "false", "Kennesaw State", "fbs", "24", "Jacksonville State", "fbs", "63");
        Calculations.addGame("6", "false", "TCU", "fbs", "19", "Houston", "fbs", "30");
        Calculations.addGame("6", "false", "Oregon", "fbs", "31", "Michigan State", "fbs", "10");
        Calculations.addGame("6", "false", "UNLV", "fbs", "41", "Syracuse", "fbs", "44");
        Calculations.addGame("6", "false", "Texas A&M", "fbs", "41", "Missouri", "fbs", "10");
        Calculations.addGame("6", "false", "North Carolina", "fbs", "24", "Pittsburgh", "fbs", "34");
        Calculations.addGame("6", "false", "Louisville", "fbs", "27", "SMU", "fbs", "34");
        Calculations.addGame("6", "false", "Wisconsin", "fbs", "52", "Purdue", "fbs", "6");
        Calculations.addGame("6", "false", "Northern Illinois", "fbs", "34", "Massachusetts", "fbs", "20");
        Calculations.addGame("6", "false", "Tulsa", "fbs", "7", "Army", "fbs", "49");
        Calculations.addGame("6", "false", "Penn State", "fbs", "27", "UCLA", "fbs", "11");
        Calculations.addGame("6", "false", "NC State", "fbs", "30", "Wake Forest", "fbs", "34");
        Calculations.addGame("6", "false", "Virginia", "fbs", "24", "Boston College", "fbs", "14");
        Calculations.addGame("6", "false", "Air Force", "fbs", "7", "Navy", "fbs", "34");
        Calculations.addGame("6", "false", "UAB", "fbs", "20", "Tulane", "fbs", "71");
        Calculations.addGame("6", "false", "Ball State", "fbs", "42", "Western Michigan", "fbs", "45");
        Calculations.addGame("6", "false", "Stanford", "fbs", "7", "Virginia Tech", "fbs", "31");
        Calculations.addGame("6", "false", "Ohio State", "fbs", "35", "Iowa", "fbs", "7");
        Calculations.addGame("6", "false", "Georgia", "fbs", "31", "Auburn", "fbs", "13");
        Calculations.addGame("6", "false", "South Carolina", "fbs", "3", "Ole Miss", "fbs", "27");
        Calculations.addGame("6", "true", "Northwestern", "fbs", "24", "Indiana", "fbs", "41");
        Calculations.addGame("6", "false", "UConn", "fbs", "29", "Temple", "fbs", "20");
        Calculations.addGame("6", "false", "Marshall", "fbs", "52", "App State", "fbs", "37");
        Calculations.addGame("6", "false", "Toledo", "fbs", "30", "Miami (OH)", "fbs", "20");
        Calculations.addGame("6", "false", "Akron", "fbs", "20", "Bowling Green", "fbs", "27");
        Calculations.addGame("6", "false", "Charlotte", "fbs", "55", "East Carolina", "fbs", "24");
        Calculations.addGame("6", "false", "Nebraska", "fbs", "14", "Rutgers", "fbs", "7");
        Calculations.addGame("6", "false", "Oklahoma State", "fbs", "14", "West Virginia", "fbs", "38");
        Calculations.addGame("6", "false", "Vanderbilt", "fbs", "40", "Alabama", "fbs", "35");
        Calculations.addGame("6", "false", "Oregon State", "fbs", "39", "Colorado State", "fbs", "31");
        Calculations.addGame("6", "false", "Southern Miss", "fbs", "13", "Louisiana", "fbs", "23");
        Calculations.addGame("6", "false", "Coastal Carolina", "fbs", "45", "Old Dominion", "fbs", "37");
        Calculations.addGame("6", "false", "UL Monroe", "fbs", "21", "James Madison", "fbs", "19");
        Calculations.addGame("6", "false", "Arkansas State", "fbs", "18", "South Alabama", "fbs", "16");
        Calculations.addGame("6", "false", "Florida State", "fbs", "13", "Clemson", "fbs", "29");
        Calculations.addGame("6", "false", "Boise State", "fbs", "62", "Utah State", "fbs", "30");
        Calculations.addGame("6", "false", "Washington", "fbs", "27", "Michigan", "fbs", "17");
        Calculations.addGame("6", "false", "Arkansas", "fbs", "19", "Tennessee", "fbs", "14");
        Calculations.addGame("6", "false", "San José State", "fbs", "35", "Nevada", "fbs", "31");
        Calculations.addGame("6", "false", "Iowa State", "fbs", "43", "Baylor", "fbs", "21");
        Calculations.addGame("6", "false", "Minnesota", "fbs", "24", "USC", "fbs", "17");
        Calculations.addGame("6", "false", "Florida", "fbs", "24", "UCF", "fbs", "13");
        Calculations.addGame("6", "false", "Arizona State", "fbs", "35", "Kansas", "fbs", "31");
        Calculations.addGame("6", "false", "San Diego State", "fbs", "27", "Hawai'i", "fbs", "24");
        Calculations.addGame("6", "false", "Georgia Tech", "fbs", "24", "Duke", "fbs", "14");
        Calculations.addGame("6", "false", "California", "fbs", "38", "Miami", "fbs", "39");
        Calculations.addGame("6", "false", "Arizona", "fbs", "22", "Texas Tech", "fbs", "28");
    }
}